spring:
    datasource:
      username: ${RDS_USER}
      password: ${RDS_PASS}
      url: ${RDS_URL}

#      username: ${DB_USER}
#      password: ${DB_PASSWORD}
#      url: ${DB_URL}

    jpa:
        database-platform: org.hibernate.dialect.Oracle10gDialect
server:
    port: 9093