server:
  port: 9098
spring:
  application:
    name: curriculumService
  cloud:
    services:
      registrationMethod: route
  datasource:
    url: jdbc:postgresql://baasu.db.elephantsql.com:5432/qfnqeflg
    username: qfnqeflg
    password: hna9MVG8qUcelIjDsWmRrDJFM0RZrVMG
    driverClassName: org.postgresql.Driver
    tomcat:
          max-active: 3
#    username: ${RDS_USER}
#    password: ${RDS_PASS}
#    url: ${RDS_URL}
    #username: assignforce_dev
    #password: pVCwxTn3
    #url: jdbc:oracle:thin:@assignforce.chueiwozbnfz.us-east-1.rds.amazonaws.com:1521:ORCL
#    username: ${DB_USER}
#    password: ${DB_PASSWORD}
#    url: ${DB_URL}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#        database-platform: org.hibernate.dialect.Oracle10gDialect
producer:
  ribbon:
    ServerListRefreshInterval: 5000
ribbon:
  isSecure: false
security:
  basic:
    enabled: false

debug: true