spring:

# config for microservice
  application:
    name: curriculumService
  cloud:
    services:
      registrationMethod: route


  producer:
    ribbon:
      ServerListRefreshInterval: 5000
  ribbon:
    isSecure: false  #temporary allows open access to endpoint

  security:
    basic:
      enabled: false

  #Database
  datasource:
    username: assignforce_dev
    password: pVCwxTn3
    url: jdbc:oracle:thin:@assignforce.chueiwozbnfz.us-east-1.rds.amazonaws.com:1521:ORCL

#      username: ${DB_USER}
#      password: ${DB_PASSWORD}
#      url: ${DB_URL}

    jpa:
        database-platform: org.hibernate.dialect.Oracle10gDialect
server:
    port: 9093