spring:
  application:
    name: locationService
  profiles:
    active: development
  datasource:
    url: jdbc:postgresql://baasu.db.elephantsql.com:5432/fxpulxfi
    username: fxpulxfi
    password: LjLdqIrb6yw51t0Q713uZI0nIlSIVCwV
    driverClassName: org.postgresql.Driver
    tomcat:
      max-active: 2
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#  datasource:
#    username: assignforce_dev
#    password: pVCwxTn3
#    url: jdbc:oracle:thin:@assignforce.chueiwozbnfz.us-east-1.rds.amazonaws.com:1521:ORCL

#  datasource:
#    username: jeffreywu0216
#    password: 00000000
#    url: jdbc:oracle:thin:@assignforce-location.csnb7shpjqea.us-east-2.rds.amazonaws.com:1521:ORCL
#  jpa:
#    database-platform: org.hibernate.dialect.Oracle10gDialect

#  jpa:
#    database-platform: org.hibernate.dialect.Oracle10gDialect

server:
  port: 9090

cloud:
 services:
   registrationMethod: route

producer:
 ribbon:
   ServerListRefreshInterval: 5000

ribbon:
 isSecure: false

security:
 basic:
   enabled: false

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    lease: 5
#    healthcheck:
#      enabled: false
#  instance:
#    lease-expiration-duration-in-seconds: 2
#    lease-renewal-interval-in-seconds: 1