
spring:
    application:
        name: unavailableService
    #DATABASE CONFIG ISSUE: CANNOT USE ENVIRONMENT VARIABLE
    datasource:
        url: jdbc:postgresql://baasu.db.elephantsql.com:5432/dtfjfsxg
        username: dtfjfsxg
        password: dxHr1OkROL4Qa7famATXzeRyNq_tOjL0
        driverClassName: org.postgresql.Driver
        tomcat:
           max-active: 2
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect



server:
  port: 8433

producer:
  ribbon:
    ServerListRefreshInterval: 5000
ribbon:
  isSecure: false
security:
  basic:
    enabled: false


#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    lease: 5
#    healthcheck:
#      enabled: false
#  instance:
#    lease-expiration-duration-in-seconds: 2
#    lease-renewal-interval-in-seconds: 1