server:
  port: 9092
spring:
    application:
        name: batchService
    cloud:
      services:
        registrationMethod: route
    #DATABASE CONFIG ISSUE: CANNOT USE ENVIRONMENT VARIABLE
    datasource:
        url: jdbc:postgresql://baasu.db.elephantsql.com:5432/heqfqejq
        username: heqfqejq
        password: RpG4zxsNbYyrlfZAWTy3pNNa4KgTNu-g
        driverClassName: org.postgresql.Driver
        tomcat:
          max-active: 3
#        url: ${DB_URL}
#        username: ${DB_USER}
#        password: ${DB_PASSWORD}
    #HIBERNATE
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
producer:          
 ribbon:
   ServerListRefreshInterval: 5000
ribbon:
 isSecure: false  
security:
 basic:
   enabled: false