spring:
  application:
    name: gateway
  cloud:
    services:
      registrationMethod: route
    
management:
  security:
    enabled: false

producer:
  ribbon:
    ServerListRefreshInterval: 5000
ribbon:
  isSecure: false
security:
  basic:
    enabled: false

#Zuul with Eureka
zuul:
  prefix: /api
  routes:
    batch:
      path: /batch/**
      serviceId: batchService
    curriculum:
      path: /curriculum/**
      serviceId: curriculumService
    location:
      path: /location/**
      serviceId: locationService
    skill:
      path: /skill/**
      serviceId: skillService
    trainer:
      path: /trainer/**
      serviceId: trainerService
    unavailable:
      path: /unavailable/**
      serviceId: unavailableService
    userSettings:
      path: /usersettings/**
      serviceId: userSettingsService


#eureka:
#  client:
#    healthcheck:
#      enabled: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#    instance:
#      lease-expiration-duration-in-seconds: 2
#      lease-renewal-interval-in-seconds: 1

salesforce:
  oauth2:
    client:
      clientId: 3MVG9ahGHqp.k2_wb8eUMtoR38zX8fWod2YBcK5.4RRrWling4BGamz7JanMJTUGcXxI9qda4fQh3xU0Q9EBH
      clientSecret: ${OAUTH_CLIENT_SECRET}
      accessTokenUri: https://revature--int1.cs17.my.salesforce.com/services/oauth2/token
      revokeTokenUri: https://revature--int1.cs17.my.salesforce.com/services/oauth2/revoke
      userAuthorizationUri: https://revature--int1.cs17.my.salesforce.com/services/oauth2/authorize?prompt=login
      tokenName: authorization_code
      authenticationScheme: header
      clientAuthenticationScheme: form
      grantType: authorization_code
      preEstablishedRedirectUri: https://assignforcebackend.cfapps.io/login
      #registeredRedirectUri: https://localhost/login
      #useCurrentUri: false
    resource:
      userInfoUri: https://revature--int1.cs17.my.salesforce.com/services/oauth2/userinfo
#  ignored: /api/v2/google/**
server:
  port: 80
#  ssl:
#    keyStore: classpath:keystore.jks
#    keyStorePassword: password
#    keyStoreType: jks
#    keyAlias: selfsigned
 
frontEndUrl: https://assignforcefrontend.cfapps.io/

tokenEncryption:
  password: ${ENC_PASS}
  salt: ${ENC_SALT}
