server:
  port: 9091 # I don't think this is actually needed outside of local eureka, but whatever

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    lease: 5
#    healthcheck:
#      enabled: false
#  instance:
#    lease-expiration-duration-in-seconds: 2
#    lease-renewal-interval-in-seconds: 1
spring:
  application:
    name: settingsService  # for example trainerService
  cloud:
    services:
      registrationMethod: route
  data:
    mongodb:
      uri: mongodb://setting:settingpw@ds245347.mlab.com:45347/setting
  

producer:
  ribbon:
    ServerListRefreshInterval: 5000
ribbon:
  isSecure: false
security:
  basic:
    enabled: false
